#ifndef ROS_VOLUME_COMMON_UTILITIES_H
#define ROS_VOLUME_COMMON_UTILITIES_H

enum NotificationLevel {  UNDEFINED_LEVEL = 0,
    DEBUG_LEVEL,
    INFO_LEVEL,
    WARNING_LEVEL,
    DANGER_LEVEL
};

#endif //ROS_VOLUME_COMMON_UTILITIES_H
